export const API_URL = {
  AUTH: {
    LOGIN: '/login',
    CHANGE_PASSWORD: '/change-password',
    SWITCH_ACCOUNT: '/switch-account',
    ACCOUNTS: '/accounts',
  },
  FREELANCER: {
    ASSIGN_PROJECT_LIST: '/freelancer/list',
    EXPERIENCE: '/freelancer/experience',
    EMAIL_SIGNUP: '/freelancer/signup',
    SIGNUP_STEPS: '/freelancer/steps',
    PROFIlE_LINKS: '/freelancer/profile-links',
    EDUCATION: '/freelancer/education',
    PROJECT: '/freelancer/project',
    ROLE: '/freelancer/role',
    SKILL: '/freelancer/skill',
    HOURLY_RATE: '/freelancer/hourly-rate',
    WORK_DETAILS: '/freelancer/work-details',
    CONTACT_DETAILS: '/freelancer/contact-details',
    PROJECT_DETAILS: '/details/freelancer',
  },
  CLIENT: {
    PROJECT_LIST: '/client/list',
    EMAIL_SIGNUP: '/client/signup',
    PROJECT_DETAILS: '/details/client',
  },
  PROJECT: {
    TITLE: '/title',
    SKILL: '/skills',
    BUDGET: '/budget',
    REQUIREMENTS: '/requirements',
    APPLY: '/apply',
  },
  COMPANY: {},
  RECRUITER: {
    EMAIL_SIGNUP: '/recruiter/signup',
    JOB_LIST: '/recruiter/list',
  },
  JOB_POST: {},
  LIST: '/list',
  SKILL: '/skill',
  SERVICES: '/services',
  DETAILS: '/details',
  PROFILE: '/profile',
  CLOSE_ACCOUNT: '/close-account',
}
